import logging
import os
from typing import Dict

import sendgrid
from sendgrid.helpers.mail import Content, Email, Mail, To
from agents import Agent, function_tool

logger = logging.getLogger(__name__)


@function_tool
def send_email(subject: str, html_body: str) -> Dict[str, str]:
    """Send an email with the given subject and HTML body."""
    api_key = os.environ.get("SENDGRID_API_KEY")
    from_addr = os.environ.get("EMAIL_FROM")
    to_addr = os.environ.get("EMAIL_TO")

    if not all([api_key, from_addr, to_addr]):
        raise EnvironmentError(
            "SENDGRID_API_KEY, EMAIL_FROM, and EMAIL_TO must all be set to send email."
        )

    sg = sendgrid.SendGridAPIClient(api_key=api_key)
    mail = Mail(Email(from_addr), To(to_addr), subject, Content("text/html", html_body)).get()
    response = sg.client.mail.send.post(request_body=mail)
    logger.info("Email sent — status %s", response.status_code)
    return {"status": "success", "status_code": str(response.status_code)}


INSTRUCTIONS = """You are able to send a nicely formatted HTML email based on a detailed research report.
You will be provided with a markdown report. Convert it into clean, well-presented HTML and send it 
with an appropriate subject line that captures the essence of the report topic.

HTML formatting guidelines:
- Use a clean, readable font (Georgia or similar serif for body)
- Include a styled header with the report title
- Use proper heading hierarchy (h1, h2, h3)
- Style blockquotes and lists attractively
- Add a footer noting it was generated by Deep Researcher
- Max width 700px, centred, with generous padding"""

email_agent = Agent(
    name="EmailAgent",
    instructions=INSTRUCTIONS,
    tools=[send_email],
    model="gpt-4o-mini",
)
